logging:
  level:
    root: error

game-of-three:
  mode: AUTO
  player-name: Player1
  opponent-name: Player2
  rabbitmq:
    username: guest
    password: guest
    queues-url: http://localhost:15672/api/queues/%2F